# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Md Mahin
tagline:          'A Jekyll theme'
description:      ''
url:              
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5


github:
  repo:           

theme: jekyll-theme-leap-day
